import type { Metadata } from "next";
import { Inter, Fira_Code } from "next/font/google";
import "../globals.css";
import Providers from "../providers";
import Footer from "@/components/ui/layout/footer/Footer";
import Header from "@/components/ui/layout/header/Header";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayoutWithFooter({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${firaCode.variable} antialiased`}>
        <Providers>
          <div className='flex flex-col relative w-full'>
            <div className='flex w-full'>
              <Header />
              <main className='w-full'>{children}</main>
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
